Adds the ability to define an escalation policy for the manage incidents API
PagerDuty/go-pagerduty pull request #273
Opened 2021-02-15 08:46 UTC by evnsio

2021-02-20 02:55 UTC, theckman approved these changes

2021-02-20 21:26 UTC, theckman requested changes

2021-02-20 21:26 UTC, theckman commented on incident.go
> +	EscalationPolicy *EscalationPolicy `json:"escalation_policy,omitempty"`
While I know this is technically an `EscalationPolicy`, looking at the [PagerDuty API documentation](https://developer.pagerduty.com/api-reference/reference/REST/openapiv3.json/paths/~1incidents/put) it seems like this expects the [APIObject](https://pkg.go.dev/github.com/PagerDuty/go-pagerduty#APIObject) subset of the `EscalationPolicy` type.

I'm not sure if the PagerDuty will always return success if we rendered the other `EscalationPolicy` fields in the JSON document. That makes me think we should update this to be an `*APIObject`.

What are your thoughts?

2021-03-08 03:42 UTC, theckman commented
@evnsio I wanted to see if you saw my comment above, and whether you might have the spare cycles to make the suggested iteration?

2021-03-18 06:43 UTC, theckman commented
@evnsio I wanted to ping again to see if you could make the `*APIObject` change above. This is looking like it'll soon be the only thing left open for `v.1.4.0`.

2021-03-19 14:21 UTC, evnsio commented
Sorry I completely missed these notifications.  I'll take a look over the weekend if that works?

2021-03-19 23:39 UTC, theckman commented
@evnsio absolutely! I really appreciate you making the time.

2021-04-15 18:22 UTC, theckman commented
@evnsio just wanted to ping a final time. This is the final item outstanding for `v1.4.0`, and I'd like to get us towards releasing that. If you're not free it's no sweat, please let me know and I'm happy to make this change.

2021-04-20 08:20 UTC, theckman commented
Thank you for raising this PR / feature request. I've raised a complimentary PR (#323) that supersedes this one. I'll close this PR at this time.

Although we did not get to merge your PR, we appreciate the contribution!

2021-04-20 08:20 UTC, closed without merging