return nil instead of resp on error
PagerDuty/go-pagerduty pull request #278
Opened 2021-02-20 06:36 UTC by blockpane

Prevent nil reference on error, resolves 274

2021-02-20 17:56 UTC, theckman approved these changes

2021-02-20 21:21 UTC, theckman requested changes

2021-02-20 21:21 UTC, theckman commented on event.go
> +		return  nil, fmt.Errorf("failed to action request: %w", err)
Would you be able to `go fmt` this file? Just noticed the whitespace before `nil` when getting ready to merge.

2021-02-26 01:19 UTC, theckman commented
@blockpane wanted to ping again to see if you had a moment to remove the leading whitespace on your change. If not give me a shout.

2021-03-01 02:34 UTC, blockpane commented
@theckman Sorry, just caught this request, should be fixed.

2021-03-06 03:28 UTC, theckman approved these changes

2021-03-07 23:04 UTC, merged

2021-03-07 23:06 UTC, theckman commented
@blockpane thank you for this contribution. It'll probably still be a few days until v1.4.0 is out, and it'll be included there.

If you or anyone else is running into issues with this actively, please give us a shout via a GitHub issue and I can work on backporting just that change as v1.3.1.