Return APIError from V2 Event API.
PagerDuty/go-pagerduty pull request #368
Opened 2021-10-06 05:51 UTC by abhishekrb19

This patch does the following:
- Return `APIError` instead of `error` from V2 Event APIs. This will be consistent with the other APIs. Since `APIError` implements the `error` interface, callers could leverage the helper methods associated with `APIError` such as `RateLimited()`, `NotFound()`, etc.

- Fix a few typos in the code base.

2021-10-18 02:02 UTC, theckman commented
@abhishekrb19 might you have some time soon to look at the requested changes?

2021-10-22 04:43 UTC, abhishekrb19 commented
@theckman, thank you for the review and reminder.
You're right - I missed the documentation of `APIError` - that it was designed to work only with the REST API. Also, the error response is different for the EventV2 API and returns only a small number of response codes - https://developer.pagerduty.com/api-reference/b3A6Mjc0ODI2Nw-send-an-event-to-pager-duty.

I adapted your recommendation to use `EventsAPIV2Error` instead of `EventsAPIError` to avoid ambiguity since there is also an Events V1 API where the structure of JSON response is different.

2021-11-09 05:03 UTC, theckman requested changes
I've noticed a few things that should probably be adjusted before merging this PR.

I did also notice that the `ManageEvent*` method isn't included in this change, but it will need to be. I think to do this we'll need to create separate `checkResponse` and `getErrorFromResponse` methods for the Events V2 API calls within the `client.go` file.

2021-12-09 06:00 UTC, theckman commented
@abhishekrb19 might you have the time to make the requested changes, so that this can make it into v1.5.0?

2022-02-05 08:32 UTC, closed without merging

2022-04-13 01:19 UTC, abhishekrb19 commented
@theckman, sorry for not getting back earlier! Thank you for addressing the comments!