add extension enable
PagerDuty/go-pagerduty pull request #403
Opened 2021-11-22 13:48 UTC by zonorti

Closes #398
Added EnableExtensionWithContext function which sends an empty POST request to the API

2021-11-25 20:07 UTC, theckman requested changes
Thank you for the contribution. I've one small requested change around the name of the method.

2021-11-26 21:37 UTC, theckman approved these changes
Thank you so much! This one will also merged in shortly, either v1.6.0 (or v1.5.0).

2021-12-17 14:23 UTC, merged

2021-12-17 15:20 UTC, ChezCrawford commented
I did see that but figured with your comment above that you didn't have a strong preference either way. Is there a problem with it being in 1.5.0?

2021-12-17 15:22 UTC, theckman commented
Going to take me forever to craft the release notes... 😅

2021-12-17 15:23 UTC, ChezCrawford commented
@theckman: my apologies though.  For some reason I thought you didn't have merge permissions and was trying to help out.  I just realized that is incorrect.

2021-12-17 15:25 UTC, theckman commented
No sweat! I appreciate you trying to help move things forward and being biased to action. 👍👍

2021-12-17 15:30 UTC, ChezCrawford commented
heh this isn't my favorite API either 😉