feat: Add support for fetching Audit Records
PagerDuty/go-pagerduty pull request #408
Opened 2021-12-22 00:48 UTC by t-junjie

See issue [394](https://github.com/PagerDuty/go-pagerduty/issues/394)

2022-01-08 02:14 UTC, theckman requested changes
Thank you so much! This looks almost ready, with a few small requested changes.

Could you also squash your commits down to a single one just to help keep the history cleaner once it's merged?

2022-01-08 02:14 UTC, theckman commented on audit.go
> +	Actors           []Actor          `json:"actors,omitempty"`
Let's switch this to be `[]APIObject`, I'll explain why in my comment on the `Actor` type definition...

2022-01-08 02:14 UTC, theckman commented on audit.go
> +type Actor APIObject
I think we should avoid this becoming a named type. If PagerDuty ever adds any functionality in the future, where something else is referred to as an "actor", we can no longer use this name without a breaking change. I think using it directly as an `APIObject` is more clear to consumers that it's not a hydrated object.

2022-01-08 02:14 UTC, theckman commented on audit.go
> +type Resource APIObject
I have the same thoughts here as I do about `Actor`.

2022-01-08 02:14 UTC, theckman commented on audit.go
> +func (c *Client) ListAuditRecords(ctx context.Context, o ListAuditRecordsOptions) (*ListAuditRecordsResponse, error) {
I think per issue #270 we should return `(ListAuditRecordsResponse, error)`.

2022-01-08 02:14 UTC, theckman commented on audit.go
> +// params or default criteria, processing paginated responses.
Could you add these to sentences to the end of this comment:

```
The include function decides whether or not to include a specific AuditRecord in the final result. If the include function is nil, all audit records from the API are included by default.
```

The rest looks good!

2022-01-08 02:14 UTC, theckman commented on client.go
> +}
Thank you for doing all of this! 👍

2022-01-11 14:16 UTC, t-junjie commented
I pulled in changes from `master` and made the relevant changes as requested above. 
It looks like I overwrote some of the commits when I squashed them when I did a `git rebase`, causing the previous review to be "outdated". Sorry about that

2022-01-16 04:29 UTC, theckman commented
The tests are failing:

```
=== RUN   TestAudit_List
    audit_test.go:94: values not equal (-want / +got):
          interface{}(
        - 	&pagerduty.ListAuditRecordsResponse{
        - 		Records: []pagerduty.AuditRecord{
        - 			{
        - 				ID:               "PDRECORDID4_UPDATED_USERS_NOTIFI"...,
        - 				ExecutionTime:    "2020-06-04T15:30:16.272Z",
        - 				ExecutionContext: pagerduty.ExecutionContext{...},
        - 				Actors:           []pagerduty.APIObject{...},
        - 				...
        - 			},
        - 		},
        - 		Limit: 10,
        - 	},
        + 	pagerduty.ListAuditRecordsResponse{
        + 		Records: []pagerduty.AuditRecord{
        + 			{
        + 				ID:               "PDRECORDID4_UPDATED_USERS_NOTIFI"...,
        + 				ExecutionTime:    "2020-06-04T15:30:16.272Z",
        + 				ExecutionContext: pagerduty.ExecutionContext{...},
        + 				Actors:           []pagerduty.APIObject{...},
        + 				...
        + 			},
        + 		},
        + 		Limit: 10,
        + 	},
          )
--- FAIL: TestAudit_List (0.00s)
````

2022-01-17 03:55 UTC, t-junjie commented
I made the appropriate changes and the test has passed.

2022-01-19 06:06 UTC, theckman approved these changes

2022-01-19 06:08 UTC, merged