Add raw incidents metrics
PagerDuty/go-pagerduty pull request #481
Opened 2023-05-04 07:55 UTC by MaggotMouth

Implement endpoints for single and multiple raw incident metrics

https://developer.pagerduty.com/api-reference/b3A6Mjc0ODExMw-get-raw-data-single-incident

https://developer.pagerduty.com/api-reference/c2d493e995071-get-raw-data-multiple-incidents

This was previously done in PRs #347 and #422 which have gone stale.

2024-01-31 22:58 UTC, krav commented
@ChuckCrawford @theckman Hi! Can we get this reviewed? Been looking to use this endpoint. Thanks!

2024-02-01 14:26 UTC, ChuckCrawford requested changes
Thank you for the PR! If would wouldn't mind making a few changes we can get this merged...

2024-02-01 14:26 UTC, ChuckCrawford commented on analytics.go
> +		"X-EARLY-ACCESS": "analytics-v2",
They probably were at the time you put up the PR but these APIs are no longer "Early Access"

2024-02-01 14:26 UTC, ChuckCrawford commented on analytics.go
> +func (c *Client) GetRawDataSingleIncident(ctx context.Context, id string) (RawData, error) {
Could we update the signatures to return a pointer to the result? e.g. `func (c *Client) GetRawDataSingleIncident(ctx context.Context, id string) (*RawData, error)`

2024-02-01 14:26 UTC, ChuckCrawford commented on analytics.go
> +func (c *Client) GetRawDataSingleIncident(ctx context.Context, id string) (RawData, error) {
A few nitpicky comments about the function names: could we name these two functions after their [OpenAPI Operation Ids](https://github.com/PagerDuty/api-schema/blob/55f11455b56cd1a829e0a949ebba744087c75172/reference/REST/openapiv3.json#L18401): `getAnalyticsIncidentsById` and `getAnalyticsIncidents`?

2024-02-01 14:26 UTC, ChuckCrawford commented on analytics.go
> +type RawData struct {
Could we name this `AnalyticsRawIncident` ?

2024-02-01 14:26 UTC, ChuckCrawford commented on analytics.go
> +type RawDataResponse struct {
This would be `AnalyticsRawIncidentsResponse`

2024-02-01 14:26 UTC, ChuckCrawford commented on analytics.go
> +type RawDataRequest struct {
This would be `AnalyticsRawIncidentsRequest`

2024-02-02 05:53 UTC, MaggotMouth commented
Thanks for the review @ChuckCrawford - I've made the changes as requested and updated the associated tests.

2024-02-02 13:35 UTC, ChuckCrawford approved these changes
Thank you for your contribution @MaggotMouth.

2024-02-02 13:36 UTC, merged

2025-03-15 16:42 UTC, Tyrael commented
@ChuckCrawford is there any ETA for v1.9.0? this was merged more than a year ago but there were no releases since.