adding support for license and licenses allocated based operations #480
PagerDuty/go-pagerduty pull request #494
Opened 2023-09-02 00:06 UTC by gerardocorea

2023-09-18 17:28 UTC, ChuckCrawford commented on license.go
> +func (c *Client) ListLicensesWithContext() (*ListLicensesResponse, error) {
The *WithContext() methods should accept a `context.Context` parameter. The newly added Event Orchestration APIs should give you an example of this: https://github.com/PagerDuty/go-pagerduty/blob/main/event_orchestration.go#L73-L90.

2023-09-18 17:34 UTC, ChuckCrawford requested changes
Thank you for putting up this PR. If we can get the method signatures reworked to properly handle the request context [comment here](https://github.com/PagerDuty/go-pagerduty/pull/494/files#r1329067020) we should be looking alright.

2023-09-18 17:35 UTC, ChuckCrawford commented on license.go
> +func (c *Client) ListLicensesWithContext() (*ListLicensesResponse, error) {
Could we also remove the non-context methods since that is now a deprecated pattern?

2023-09-20 01:10 UTC, gerardocorea commented
> Thank you for putting up this PR. If we can get the method signatures reworked to properly handle the request context [comment here](https://github.com/PagerDuty/go-pagerduty/pull/494/files#r1329067020) we should be looking alright.

Appreciate the feedback, made the requested changes.

2023-09-20 21:53 UTC, ChuckCrawford approved these changes
Thank you for your contribution @gerardocorea.

2023-09-20 21:53 UTC, merged