[CSGI-1984] Add `From` field to `ListResponsePlays` method options
PagerDuty/go-pagerduty pull request #502
Opened 2023-10-31 21:26 UTC by imjaroiswebdev

This update addresses `ListResponsePlays` method lacking of the capability for setting the **From** header value [required](https://developer.pagerduty.com/api-reference/6aa5ad7adec98-list-response-plays#request-headers) for making valid API calls to the corresponding endpoint, as a result, each call to this method would be returning the following error...

> "HTTP response with status code 400 does not contain Content-Type: application/json"

2023-11-01 15:07 UTC, ChuckCrawford requested changes
If we are going to proceed with this change let's tighten up the `Client.get` function signature. See the in-line comment for more detail.

2023-11-02 18:34 UTC, imjaroiswebdev commented on client.go
> +	var h = make(map[string]string)
Thank you @ChuckCrawford for the heads-up. However I swapped my approach to adding a new `Client.getWithHeaders` method, therefore We can avoid this unneeded change on `Client.get`. So this suggestion is no longer applicable.

2023-11-02 18:34 UTC, imjaroiswebdev commented on client.go
> +func (c *Client) get(ctx context.Context, path string, headers ...map[string]string) (*http.Response, error) {
Thank you @ChuckCrawford for the heads-up. However I swapped my approach to adding a new `Client.getWithHeaders` method, therefore We can avoid this unneeded change to `Client.get` signature. So this suggestion is no longer applicable.

2023-11-02 19:48 UTC, ChuckCrawford approved these changes

2023-11-02 19:49 UTC, merged