fix: require From when snoozing an incident
PagerDuty/go-pagerduty pull request #541
Opened 2024-10-04 20:58 UTC by adamdecaf

The API docs list From as a reqired header.

https://developer.pagerduty.com/api-reference/fc871396fb23f-snooze-an-incident#request-headers

2024-10-04 21:03 UTC, adamdecaf commented
This is a breaking change but the snooze calls don't work currently, so they're already broken.

2024-12-09 15:43 UTC, adamdecaf commented
cc @ChuckCrawford  @imjaroiswebdev

2025-01-02 18:49 UTC, ChezCrawford commented on incident.go
> +		"from": from,
nit: use upper-case header names to be consistent with the other methods and the documentation.
```suggestion
		"From": from,
```

2025-01-02 18:51 UTC, ChezCrawford commented on incident.go
> +	headers["from"] = from
nit: same as above.
```suggestion
	headers["From"] = from
```

2025-01-02 18:56 UTC, ChezCrawford requested changes
If you don't mind addressing the tiny comments I would be happy to get this merged.

2025-01-02 18:56 UTC, ChezCrawford commented on incident_test.go
> -	err := client.SnoozeIncident(id, duration)
It would be nice if we actually verified the `From` header was being sent here in the test. You can see https://github.com/PagerDuty/go-pagerduty/blob/0ef8f340dd3cab97a37f8149760b64a45510c036/incident_test.go#L958-L1007 as an example.

2025-01-02 19:41 UTC, adamdecaf commented on incident.go
> +		"from": from,
Fixed

2025-01-02 19:41 UTC, adamdecaf commented on incident.go
> +	headers["from"] = from
Fixed

2025-01-02 19:41 UTC, adamdecaf commented on incident_test.go
> -	err := client.SnoozeIncident(id, duration)
Fixed

2025-01-02 19:41 UTC, adamdecaf commented
@ChezCrawford thanks - should be g2g now

2025-01-02 20:27 UTC, ChezCrawford commented
Ahhh. As I am coming out of my holiday-vacation-fog I am realizing that this is actually a breaking change for some users. The `From` header is only required when using an Account API Key or an App OAuth Token. Clients authenticating with User API Keys are currently able to use this function without issue.

If we are going to make a breaking change here I am tempted to ask that we do this the _right way_ by adding a `SnoozeIncidentOptions` struct with `From` and `Duration` fields. Since the other "write incident" functions currently work the way you have this implemented we can leave this as-is.

2025-01-02 20:44 UTC, adamdecaf commented
I can make that change to use a struct. Yes, it's breaking but for me Snooze wasn't even working without this.

2025-01-02 21:23 UTC, ChezCrawford commented
> Yes, it's breaking but for me Snooze wasn't even working without this.

You are likely using one of the two types of tokens I mentioned above. I did verify that it works correctly with User API Keys right now.

>  I can make that change to use a struct.

I think that is the best move here. If we are going to make a breaking change let's change it to the "correct" thing that will work properly for everyone.

2025-01-06 15:25 UTC, ChuckCrawford approved these changes
Note that this PR makes a breaking change in order to add support for the snooze incident API with Account API Keys and App Tokens.

2025-01-06 15:25 UTC, merged